### ISSUE TITLE
str object not callable in print line

### ISSUE THREAD

**Issue by dawson6** [LLNL/ATS#31]
On a Toss system, I am receiving this issue with an updated print line.

It is happening here:
                for v in brothers:
                    print("testlist[%d].set(%s, 'Previously ran.') # %s"
                          (v.serialNumber - 1, v.status.name, v.name), file=fc)

Here is the python error:

Traceback (most recent call last):
  File "/usr/WS2/dawson/git-mercury-ats-new/atsmercury_back_end", line 483, in <module>
    result = manager.core()
  File "/usr/apps/ats/7.0.4/lib/python2.7/site-packages/ats/management.py", line 918, in core
    self.continuationFile(interactiveTests)
  File "/usr/apps/ats/7.0.4/lib/python2.7/site-packages/ats/management.py", line 985, in continuationFile
    (v.serialNumber - 1, v.status.name, v.name), file=fc)
TypeError: 'str' object is not callable

**Comment by dawson6** [comment]
New line is this:

         print("testlist[%d].set(%s, 'Previously ran.') # %s"
                 (v.serialNumber - 1, v.status.name, v.name), file=fc)

Old line was this:
         print >>fc, "testlist[%d].set(%s, 'Previously ran.') # %s" % \
                       (v.serialNumber-1, v.status.name, v.name)

**Comment by dawson6** [comment]
I added the continuation character but issue still arises.
